### ISSUE TITLE
Create needed files for documentation

### ISSUE THREAD

**Issue by leinson** [Ilmastokompassi/Ilmastokompassi#12]
- [x] Product Backlog
- [x] Sprint Backlog
- [x] Hour log (Tuntikirjanpito)
- [x] Definition of Done
- [x] Workflow guide ( https://github.com/piryopt/pienryhmien-optimointi/blob/main/documentation/workflow_guide.md )
- [x] ReadMe

**Comment by trickwide** [comment]
Preliminary README.md has been added by @mfaarni  and other needed documentation has been done previously. Closing this. @trickwide will do README.md in English on issue #64
