### ISSUE TITLE
Setup staging and production PostgreSQL instances

### ISSUE THREAD

**Issue by trickwide** [Ilmastokompassi/Ilmastokompassi#132]
[University of Helsinki is offering us PostgreSQL 14 instances,](https://wiki.helsinki.fi/display/SO/PostgreSQL) let's use them for the staging and production environments.

- [x] Apply for staging instance
- [x] Apply for production instance

**Comment by PaulusParssinen** [comment]
I believe we will use [the PostgreSQL cluster provided by the University of Helsinki](https://github.com/HY-TKTL/TKT20007-Ohjelmistotuotantoprojekti/tree/master/openshift#tietokannat) for both staging and production environments.
