### ISSUE TITLE
Prep for sprint review/client meeting

### ISSUE THREAD

**Issue by leinson** [Ilmastokompassi/Ilmastokompassi#14]
- [x] Book a meeting room
- [x] Decide Agenda

**Comment by trickwide** [comment]
Meeting was booked on Friday 08.09.2023. Meeting will be held on Tuesday 12.09.2023 08:00-10:00 with project team and customer representation attending. Preliminary agenda has been selected but final agenda will be set on Monday, day before the meeting.

**Comment by Desipeli** [comment]
Done
