### ISSUE TITLE
Setup continuous integration for the project using GitHub Actions

### ISSUE THREAD

**Issue by PaulusParssinen** [Ilmastokompassi/Ilmastokompassi#16]
The continuous integration ensures that pushed code follows the pylint rules and that the all tests succeed.

Depends on #10 and #15

**Comment by trickwide** [comment]
First CI version has been added to GitHub Actions, still requires #15 to be done before we close this. Need to add Pylint mentions into the main.yml in .github/workflows

**Comment by trickwide** [comment]
#15 has been closed and all tasks have been fulfilled. Closing.
