### ISSUE TITLE
Implement group session creation functionality in frontend

### ISSUE THREAD

**Issue by trickwide** [Ilmastokompassi/Ilmastokompassi#232]
- [x] Design addition to current user interface
- [x] Implement necessary code to frontend
- [x] Add group session id length validation and other validation that is deemed necessary
- [x] Button for group creation
- [x] Tests

**Comment by leinson** [comment]
Done, except for the group token in the upright corner, and information about the group on the summary-page.

**Comment by trickwide** [comment]
Group session id length validation is in frontend and backend. E2E tests were introduced on #268 and group creation & button on #253
