### ISSUE TITLE
Create page for fact quiz

### ISSUE THREAD

**Issue by trickwide** [Ilmastokompassi/Ilmastokompassi#239]
- [x] Routing for the new fact quiz page
- [x] User interface (re-use current survey components, if usable)
- [x] Functionality to handle the answers
- [x] Cypress tests

When user is finished with selecting their answer they press a button, correct answer is showed and user gets a button that redirects them to next question.

Correct answers are displayed in green.

**Comment by trickwide** [comment]
Frontend route currently is `path: '/tietovisa/:questionId',`, which can be found in `router.jsx`. We need to build backend api route(s) after repository and services have been created.

**Comment by leinson** [comment]
Tests not implemented, because the content is not in its final form.

**Comment by trickwide** [comment]
Cypress E2E tests done on pull request #407, only thing we need now is Jest unittests.

**Comment by trickwide** [comment]
Closing issue as requirements have been met. Not doing Jest unittests as there is still plenty of moving parts regarding the whole application. This has been confirmed by @PaulusParssinen
