### ISSUE TITLE
Show both individual and group results

### ISSUE THREAD

**Issue by trickwide** [Ilmastokompassi/Ilmastokompassi#305]
- [x] Group results are displayed after 5 different answers with group tag
- [x] Figure out what the summary page looks like without group results
- [x] Display group averages
- [x] hide group results when not in group
- [x] Automatic reload of group stats component
- [x] backend test to the group service
- [x] frontend cypress, does group results show correctly

**Comment by leinson** [comment]
All results (the donut) now show, so there is essentially only the tests left.

**Comment by leinson** [comment]
- Blocked by lack of proper e2e test setup. work in progress. 
- Backend unit tests can be made by refactoring the function that counts the points.

**Comment by leinson** [comment]
Backend tests made, now only blocked by test setup
