### ISSUE TITLE
General summary page for group results (no individual results).

### ISSUE THREAD

**Issue by trickwide** [Ilmastokompassi/Ilmastokompassi#306]
- [x] Design what the general summary page for group results works (basicly just removing the individual profile stuff)
- [x] Create route for the page
- [x] Frontend code
- [x] donut fixes
- [ ] cypress tests

**Comment by leinson** [comment]
This is done, just the tests still to make. 

Maybe some visual fixes if there is extra time (not necessary).

**Comment by leinson** [comment]
- Blocked by lack of proper e2e test setup. work in progress

**Comment by trickwide** [comment]
Currently blocked by Cypress refactoring done by @PaulusParssinen

**Comment by PaulusParssinen** [comment]
As per the comment in #368, cypress tests are no longer blocked.

**Comment by trickwide** [comment]
Added two cypress tests that test access to the group summary page after group creation/joining. These can be reviewed from branch `group-summary-cypress`. We have to collectively discuss how to implement the necessary helper functionalities, so that it allows for further test cases that display the actual climate role for the group.

Personally I don't have time left to do this during sprint 5.

**Comment by trickwide** [comment]
As per pull request #462: 
There is some weird Cypress magic happening currently and the group summary page doesn't render climate roles of group, which blocks generating further tests. Need to find the root cause of the bug.
