### ISSUE TITLE
As a developer, I want the code base to be maintainable

### ISSUE THREAD

**Issue by leinson** [Ilmastokompassi/Ilmastokompassi#368]
Refactoring and reviewing of code needed in all components.
- Backend
  - [x] API error handling
  - [x] Factor the API survey, quiz and group routes to form logical units
- Frontend
  - [x] Misc. UI consistency work
- Testing
  - Cypress
    - [x] Use `data-testid` instead of `id` attributes
    - [x] Use `beforeEach(() => ...)` to reduce repeated logic before each test
  - Pytest

**Comment by trickwide** [comment]
@PaulusParssinen is currently working on refactoring Cypress tests

**Comment by PaulusParssinen** [comment]
* Cypress refactoring in-progress
  * Group creation test refactored. Rest of cypress test suite is incomplete. (#414)

**Comment by leinson** [comment]
Paulus has done API's
