### ISSUE TITLE
User can use the site in an accessible way

### ISSUE THREAD

**Issue by leinson** [Ilmastokompassi/Ilmastokompassi#369]
- [x] Check each MUI-component in accessible way
- [x] All self made components need aria-labels (or change them into react components)
- [x] Test with different size background - will the text on the frontpage show better? Otherwise a faded card behind the heading
- [x] Is everything on the page  named logically?
- [x] Go through quizzes on different phones and check if they display correctly
- [x] checked pages with chromes accessibility Lighthouse tool and made changes accordingly (headerlevels changed on landing and rolesurveypage, FAQ needs still changes)

**Comment by pietatuo** [comment]
Noncomprehensive list of accessibility notes to fix

- [ ] Group icon has no label
- [ ] Textfields should be focusable 
- You can get to them by tabbing, but that might not be enough? Perhaps it needs to be the first in the tabbing order? I'll look more into that.
- [ ] Navbar focusability should also be checked, though I think the tabbing is enough there
- [ ] Ilmastorooli quiz progress bar has no label
