### ISSUE TITLE
As a test user, I can give feedback on the page

### ISSUE THREAD

**Issue by leinson** [Ilmastokompassi/Ilmastokompassi#371]
- [x] Create google forms with questions for the test users
- [x] Send form and link to site to test users
- [x] Review feedback

**Comment by trickwide** [comment]
Form has been sent to the client and we are waiting for feedback from them + contact information for test users

**Comment by hartonenolli** [comment]
At the moment 12 test users has given feedback. Thease has been reviewed.
Need more data from client test users.
Need to send the feedback to client.

**Comment by leinson** [comment]
Feedback is reviewed and the realistic suggestions have been added as issues to the backlog. Most of the feedback was positive - page is easy to use, good overall simple layout, loads quickly.

Constructive feedback on more pictures and better visual outlook, edits to the quiz and survey materials themselves, and to show more statistics on the summary page. Visual changes have already been made, just not updated to the production version.
