### ISSUE TITLE
Summary page for fact quiz

### ISSUE THREAD

**Issue by Desipeli** [Ilmastokompassi/Ilmastokompassi#400]
- [x] Fetch answers from backend
- [x] Define what information should be shown...

**Comment by trickwide** [comment]
This could be achieved by creating a summary page that displays accordion components that show the question and right answers to the said question.

**Comment by trickwide** [comment]
Requires own function in `quiz_service.py` that returns all the summary info as we need correct answers for every single question.

- [ ] Create the aforementioned function

**Comment by trickwide** [comment]
Functionalities implemented on pull request #424 that is waiting for review by @Desipeli. This issue can be closed when we have made the styling more appealing  and structured. Also needs Cypress E2E tests for the quiz summary page.

- [ ] CSS Styling
- [ ] Cypress E2E tests for quiz summary
