### ISSUE TITLE
User can navigate on the website

### ISSUE THREAD

**Issue by leinson** [Ilmastokompassi/Ilmastokompassi#44]
- [x]  #52 
- [x]  #107 
- [x] #77 
- [x] #96 
- [x]  #97 
- [x] #111 

Acceptance criteria:

- [x] There is a navigation bar on the website
- [x] The contents on the bar are clickable and move the user to the page in question
- [x] You can move from every page to another through the navigation bar

**Comment by leinson** [comment]
Removed the Kysymys tab

**Comment by PaulusParssinen** [comment]
Done.
