### ISSUE TITLE
Adjust visual elements on front page

### ISSUE THREAD

**Issue by hartonenolli** [Ilmastokompassi/Ilmastokompassi#453]
This includes mostly the **Ilmastoroolikysely** and **Oppimisvisa** cards along with "welcome" header and subheader of site.

- [x] On mobile
- [x] On desktop
- [x] Add pictures
- [x] Add new texts
- [x] Change heading levels so that they are semantical (highest up h1, then h2 ...) Accessibility testing errors about this

**Comment by trickwide** [comment]
Pull request #489 adds new images, added also new texts to roleSurvey and factQuiz cards on front page. Still need to add the front page header ("welcome" text)  and its subheader. Further visual adjustments need to be made towards mobile view especially, which are next on my task list.

**Comment by trickwide** [comment]
Pull request #494 fixes issues for card content scaling on mobile screens. Still need to adjust header and sub-header size or even font. Furthermore we should add padding between elements as the elements especially hug the mobile screen on sides.
