### ISSUE TITLE
Add graphics to pages

### ISSUE THREAD

**Issue by hartonenolli** [Ilmastokompassi/Ilmastokompassi#457]
- [x] Backround
- [x] Climateroleaccordion
- [x] Summarypage
- [x] Groupsummarypage
- [x] navbar compass
- [x] favicon compass
- [x] Landingpage cards
- [x] Landingpage climate compass
- [x] Factquiz summary page
- [x] FAQ page
- [x] Climate compass to survey pages? If it looks good

**Comment by leinson** [comment]
- Waiting on Landingpage card visuals from Inka. After this is done, change priority to small.

- Climate compass to survey pages & FAQ is not priority

**Comment by trickwide** [comment]
Landing page card visuals have been added as part of #453, priority of task has been moved from medium to small.

**Comment by leinson** [comment]
Changed size to small, only a few changes to be made if we feel like it.
