### ISSUE TITLE
Move hardcoded shorter climate role descriptions to the database.

### ISSUE THREAD

**Issue by PaulusParssinen** [Ilmastokompassi/Ilmastokompassi#485]
Move [the shorter hardcoded climate role descriptions](https://github.com/Ilmastokompassi/Ilmastokompassi/blob/87d53f2caa4f1b04766bf121335bd9cd02ca8703/frontend/src/components/roleSurvey/RoleAccordion.jsx#L14-L19) to the database.

**Comment by PaulusParssinen** [comment]
Short role descriptions added to the database. Still need to fetch and use them in the frontend.

**Comment by trickwide** [comment]
Closing issue as this has been done as of PR #527
