### ISSUE TITLE
As a team we can celebrate our project together over a luxury business lunch

### ISSUE THREAD

**Issue by leinson** [Ilmastokompassi/Ilmastokompassi#510]
- [x] choose location
- [Bistro Bryk](https://www.bistrobryk.fi/): in Arabianranta. Order from menu 

- [x] choose date
- Date has been chosen, it is Tuesday 12.12 between 10-13

**Comment by trickwide** [comment]
Luxury business lunch was held at Bistro Bryk and we can close this issue.
